site_name: Lucien-Joelle's Notebook  
site_description: 个人学习笔记和知识管理系统
site_author: Lucien-Joelle
site_url: https://lucien-joelle.github.io/notebook

# 主题配置
theme:
  name: material
  language: zh
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # 浅色模式 - 蓝紫色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式 - 深紫色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

# Markdown扩展
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true

# 插件
plugins:
  - search:
      lang: 
        - zh
        - en
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# 额外的JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 额外的CSS
extra_css:
  - stylesheets/extra.css

# 导航结构 - 基础框架，可根据需要扩展
nav:
  - 首页: index.md
  - 设计指南: 设计指南.md
  - 学习笔记:
    - 学习笔记/index.md
    - 编程语言:
      - 学习笔记/编程语言/index.md
      - Python: 学习笔记/编程语言/python.md
      - JavaScript: 学习笔记/编程语言/javascript.md
    - 算法与数据结构:
      - 学习笔记/算法/index.md
      - 基础算法: 学习笔记/算法/基础算法.md
      - 数据结构: 学习笔记/算法/数据结构.md
    - 计算机基础:
      - 学习笔记/计算机基础/index.md
      - 操作系统: 学习笔记/计算机基础/操作系统.md
      - 计算机网络: 学习笔记/计算机基础/计算机网络.md
  - 项目记录:
    - 项目记录/index.md
  - 读书笔记:
    - 读书笔记/index.md
  - 工具使用:
    - 工具使用/index.md
    - Git使用: 工具使用/git.md
    - Docker使用: 工具使用/docker.md

# 额外配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lucien-Joelle
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:your-email@example.com
      name: Email
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
      name: Twitter
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  generator: false
  version:
    provider: mike
