site_name: Lucien-Joelle's Notebook
site_description: 个人学习笔记和知识管理系统  
site_author: Lucien-Joelle
site_url: https://lucien-joelle.github.io/notebook

# 仓库配置
repo_url: https://github.com/lucien-joelle/notebook
repo_name: lucien-joelle/notebook
edit_uri: edit/main/docs/

# 主题配置 - 参考IsshikiHugh项目的简洁设计
theme:
  name: material
  language: zh
  favicon: assets/logo.svg
  logo: assets/logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
  palette:
    # 保持原有美丽配色
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: 切换到暗色模式
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

# Markdown扩展 - 参考IsshikiHugh项目的简洁配置
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
      auto_append:
        - abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic:
      mode: view

# 插件配置 - 参考IsshikiHugh项目的实用组合
plugins:
  - search:
      lang: zh
      separator: '[\s\-\.]+'
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      locale: zh
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - awesome-pages
  - macros:
      include_dir: includes

# 额外的JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 额外的CSS
extra_css:
  - stylesheets/extra.css

# 导航结构 - 参考IsshikiHugh项目的简洁架构
nav:
  - 💠 主页: index.md
  - 📚 技术积累:
    - 学习笔记/index.md
    - 编程语言:
      - 学习笔记/编程语言/index.md
      - Python: 学习笔记/编程语言/python.md
      - JavaScript: 学习笔记/编程语言/javascript.md
    - 算法: 学习笔记/算法/index.md
    - 数据库: 学习笔记/数据库/index.md
    - 网络: 学习笔记/网络/index.md
    - AI: 学习笔记/AI/index.md
    - 工具使用:
      - 工具使用/index.md
      - Git: 工具使用/git.md
      - VS Code: 工具使用/vscode.md
      - Docker: 工具使用/docker.md
  - 📝 项目记录: 项目记录/index.md
  - 📖 读书笔记: 读书笔记/index.md
  - 📝 设计指南: 设计指南.md

# 额外配置
extra:
  generator: false
  homepage: https://lucien-joelle.github.io/notebook
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucien-joelle
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:your-email@example.com
      name: Email

  consent:
    title: Cookie 同意
    description: >-
      我们使用 Cookie 来识别您的重复访问和偏好，以及
      衡量我们文档的有效性以及用户是否找到了他们要寻找的内容。
      在您同意的情况下，这有助于我们改进我们的文档。
    actions:
      - accept
      - reject

# 版权信息
copyright: Copyright &copy; 2024 Lucien-Joelle
