site_name: Lucien-Joelle's Notebook
site_description: 个人学习笔记和知识管理系统  
site_author: Lucien-Joelle
site_url: https://lucien-joelle.github.io/notebook

# 仓库配置
repo_url: https://github.com/lucien-joelle/notebook
repo_name: lucien-joelle/notebook
edit_uri: edit/main/docs/

# 主题配置 - 参考IsshikiHugh项目的简洁设计
theme:
  name: material
  language: zh
  favicon: assets/logo.svg
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
  palette:
    # 保持原有美丽配色
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: 切换到暗色模式
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

# Markdown扩展 - 参考IsshikiHugh项目的简洁配置
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# 插件配置 - 参考IsshikiHugh项目的实用组合
plugins:
  - search:
      lang: zh
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

# 额外的JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 额外的CSS
extra_css:
  - stylesheets/extra.css

# 导航结构 - 参考IsshikiHugh项目的简洁架构
nav:
  - 💠 主页: index.md
  - 📚 技术积累:
    - 学习笔记/index.md
    - 编程语言:
      - 学习笔记/编程语言/index.md
      - Python: 学习笔记/编程语言/python.md
      - JavaScript: 学习笔记/编程语言/javascript.md
    - 算法: 学习笔记/算法/index.md
    - 数据库: 学习笔记/数据库/index.md
    - 网络: 学习笔记/网络/index.md
    - 工具使用:
      - 工具使用/index.md
      - Git: 工具使用/git.md
      - VS Code: 工具使用/vscode.md
      - Docker: 工具使用/docker.md
  - 📝 项目记录: 项目记录/index.md
  - 📖 读书笔记: 读书笔记/index.md
  - 📝 设计指南: 设计指南.md

# 额外配置
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucien-joelle
      name: GitHub

# 版权信息
copyright: Copyright &copy; 2024 Lucien-Joelle
