site_name: Lucien-Joelle's Notebook
site_description: 个人学习笔记和知识管理系统  
site_author: Lucien-Joelle
site_url: https://lucien-joelle.github.io/notebook

# 仓库配置
repo_url: https://github.com/lucien-joelle/notebook
repo_name: lucien-joelle/notebook
edit_uri: edit/main/docs/

# 主题配置
theme:
  name: material
  language: zh
  favicon: assets/logo.svg
  logo: assets/logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: 切换到暗色模式
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

# Markdown扩展
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
      auto_append:
        - abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic:
      mode: view

# 插件配置
plugins:
  - search:
      lang: zh
      separator: '[\s\-\.]+'
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      locale: zh
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - awesome-pages
  # - macros:
  #     include_dir: includes

# 额外的JavaScript
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - javascripts/math-renderer.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.9.0/dist/mermaid.min.js
  - javascripts/custom.js

# 额外的CSS
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - stylesheets/extra.css

# 导航结构
nav:
  - 主页: index.md
  - 课堂笔记: 
    - 概览: 课堂笔记/index.md
    - 离散数学: 课堂笔记/离散数学.md
    - 数据结构基础: 课堂笔记/数据结构基础.md
    - 数字逻辑设计: 课堂笔记/数字逻辑设计.md
  - 技术积累:
    - 概览: 技术积累/index.md
    - markdown:
      - 概览: 技术积累/markdown/index.md
      - Typora教程: 技术积累/markdown/Typora markdown教程.md
      - markdown入门: 技术积累/markdown/新手教程.md
    - git:
      - 概览: 技术积累/git/index.md
      - git学习: 技术积累/git/git_learn.md
      - git应用: 技术积累/git/git_apply.md
    - 前端开发:
      - 概览: 技术积累/前端/index.md
      - 关于前端: 技术积累/前端/关于前端.md
      - HTML: 技术积累/前端/HTML.md
      - CSS: 技术积累/前端/CSS.md
      - JavaScript: 技术积累/前端/JS.md
      - TypeScript: 技术积累/前端/typescript.md
      - React: 技术积累/前端/React.md
      - fatch api: 技术积累/前端/fatch api.md
    - 后端开发:
      - 概览: 技术积累/后端/index.md
      - 数据库: 技术积累/后端/数据库.md
      - Go: 技术积累/后端/Go.md
    - 登录鉴权: 技术积累/登录&鉴权.md
    - api制定: 技术积累/api的制定.md
    - 编程语言:
      - 概览: 技术积累/编程语言/index.md
      - C#: 技术积累/编程语言/C#.md
    - shell脚本: 技术积累/shell脚本.md

  - 项目记录: 项目记录/index.md
  - 读书笔记:
    - 概览: 读书笔记/index.md
    - Computer Science Distilled: 读书笔记/ComputerScienceDistilled.md
  - 设计指南: 设计指南.md

# 额外配置
extra:
  generator: false
  homepage: https://lucien-joelle.github.io/notebook
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucien-joelle
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:3454410481@qq.com
      name: Email

  consent:
    title: Cookie 同意
    description: >-
      我们使用 Cookie 来识别您的重复访问和偏好，以及
      衡量我们文档的有效性以及用户是否找到了他们要寻找的内容。
      在您同意的情况下，这有助于我们改进我们的文档。
    actions:
      - accept
      - reject

# 版权信息
copyright: Copyright &copy; 2025 Lucien-Joelle



 